
Import('*')
LIBS = env['LIBS']
LIBS +=['dwarf']
env['LIBS'] = LIBS
Source('fi_sys.cc')
Source('fi.cc')
Source('compile_info.cc')
Source('debug_info.cc')
Source('util.cc')
Source('ini_reader.cc')
Source('profile.cc')
DebugFlag('REGFI')
DebugFlag('MEMFI')
DebugFlag('MPUFI')
DebugFlag('PFUFI')
DebugFlag('CACHEFI')
DebugFlag('VARFI')
DebugFlag('DPUFI')
DebugFlag('CUFI')
DebugFlag('FISYS')
DebugFlag('FI')
CompoundFlag('DFI', [ 'REGFI', 'MEMFI','VARFI','DPUFI','CUFI','FISYS'])